version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          - dependencies-{{ .Branch }}
          - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run build


